/*
5. Write multithreaded program that generates the Fibonacci series. The program should work as follows: The user will enter on 
the command line the number of Fibonacci numbers that the program is to generate. The program then will create a separate thread 
that will generate the Fibonacci numbers, placing the sequence in data that is shared by the threads (an array is probably the 
most convenient data structure). When the thread finishes execution the parent will output the sequence generated by the child 
thread. Because the parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, this will 
require having the parent thread wait for the child thread to finish.
*/

#include <stdio.h>
#include <pthread.h>

int n, fib[100];

void *generate(void *arg)
{
    fib[0] = 0;
    fib[1] = 1;
    for (int i = 2; i < n; i++)
        fib[i] = fib[i - 1] + fib[i - 2];
}

int main()
{
    pthread_t t;

    printf("Enter number of terms: ");
    scanf("%d", &n);

    pthread_create(&t, NULL, generate, NULL);
    pthread_join(t, NULL);

    for (int i = 0; i < n; i++)
        printf("%d ", fib[i]);

    return 0;
}